#!/bin/sh


CHOIX="dual vga\nvga seul\nportable\ndual hdmi\nhdmi seul\narandr"

Selec=$(echo $CHOIX | dmenu)

notify-send "$Selec"

case $Selec in 
	"portable") xrandr --output LVDS1 --auto --output VGA1 --off --output HDMI1 --off ;;
	"hdmi seul") xrandr --output HDMI1 --auto --output VGA1 --off --output LVDS1 --off ;;
	"vga seul") xrandr --output VGA1 --auto --output HDMI1 --off --output LVDS1 --off ;;
	"dual hdmi") xrandr --output LVDS1 --auto --output HDMI1 --auto --left-of LVDS1 --output VGA1 --off ;;
	"dual vga") xrandr --output LVDS1 --auto --output VGA1 --auto --left-of LVDS1 --output HDMI1 --off ;;
	"arandr") arandr ;;
esac

[ "$Selec" = "" ] || polybar_launch
[ "$Selec" = "" ] || feh --bg-fill ~/.wallpaper &



